@startuml Диаграмма контекста
title "E-Learning"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"

Person(student, "Обучающийся", "")
Person(teacher, "Преподаватель", "")
Person(admin, "Администратор", "")
Person(support, "Техподдержка", "")
' технологии лишние
System(eLearningSystem, "Система E-Learning",  "Сервис онлайн обучения", $sprite="react")

student --> eLearningSystem: Прохождение курсов, сдача тестов, получение отзывов и сертификатов.
teacher --> eLearningSystem: Создание и редактирование курсов, мониторинг успеваемости студентов, предоставление обратной связи
admin --> eLearningSystem: Управление пользователями, курсами, доступами, статистика по курсам
support --> eLearningSystem: Решение технических проблем, обновление системы


System_Ext(reserveCopy, "Сервис резервного копирования", "")
System_Ext(SSO, "SingleSignOn", "Сервис сквозного прохода")
System_Ext(notificater, "Сервис уведомлений", "Отправка уведомлений")
System_Ext(viewVideoService, "Сервис отображения видео")

eLearningSystem --> reserveCopy
eLearningSystem --> SSO
eLearningSystem --> notificater
eLearningSystem --> viewVideoService
eLearningSystem --> analyticsService

@enduml
