@startuml Диаграмма контейнеров
title "C4. Контейнеры системы электронного обучения"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Персоны
Person(student, "Обучающийся", "Прохождение курсов, сдача тестов, получение отзывов и сертификатов.")
Person(teacher, "Преподаватель", "Создание и редактирование курсов, мониторинг успеваемости студентов, предоставление обратной связи")
Person(admin, "Администратор", "Управление пользователями, курсами, доступами, статистика по курсам")
Person(support, "Техподдержка", "Решение технических проблем, обновление системы")

' Система
System_Boundary(appElearning, "Система электронного обучения") {
   
    Container(webApp, "Веб-приложение", "React", "Пользовательский интерфейс для прохождения, создания курсов и обратной связи")
    
    
        Container(APIGateway, "Апи сервис", "nGinx", "")
        Container(userService, "Контекст пользователь", "GO", "Операции над пользователями, управление данными, общение с SSO")
        Container(contentManagerService, "Сервис управления контентом", "GO", "создание, редактирование, назначение курсов")
        Container(testManagerService, "Сервис управления тестами", "GO", "создание, редактирование тестов и экзаменов")
        Container(communicationService, "Сервис обратной связи", "GO", "Обеспечение обратной связи и форумов на курсах")
        Container(statisticsService, "Сервис сбора статистики", "GO", "Собирает данные нужные для каждого рода статистики")
        Container(backupService, "Сервис резервного копирования", "GO", "Собирает данные для РК, обновляет их во внешнем сервисе")
        Container(notificater, "Сервис уведомлений","перенаправляет уведомления")
    


    Container(crone, "Планировщик", "PHP", "определяет таймауты событий внутри системы")
    Container(dbStatistics, "База данных статистики", "PostgreeSQL", "Хранение данных о пользователях, курсах, сообщениях, оцнках...")
    Container(dbContent, "База данных контента", "PostgreeSQL", "Хранение данных о пользователях, курсах, сообщениях, оцнках...")
}
'типы бд: статистики, БД Контента, sso, 


System_Ext(backupServiceInternal, "Внешний сервис резервного копирования", "")
System_Ext(SSO, "SingleSignOn", "Сервис сквозного прохода")
System_Ext(notificaterInternal, "Внешний сервис уведомлений", "Отправка уведомлений")
System_Ext(viewVideoService, "Сервис отображения видео")

Rel(student, webApp, "", "")
Rel(teacher, webApp, "", "")
Rel(admin, webApp, "", "")
Rel(support, webApp, "", "")

Rel(webApp, APIGateway, "", "")

Rel(webApp, APIGateway, "", "")
Rel(APIGateway, userService, "", "")
Rel(APIGateway, contentManagerService, "", "")
Rel(APIGateway, testManagerService, "", "")
Rel(APIGateway, statisticsService, "", "")
Rel(APIGateway, communicationService, "", "")

Rel(userService, SSO, "", "")
Rel(userService, notificater, "", "")

Rel(contentManagerService, dbContent, "", "")
Rel(contentManagerService, testManagerService, "", "")
Rel(contentManagerService, viewVideoService, "", "")
Rel(contentManagerService, notificater, "", "")
Rel(contentManagerService, communicationService, "", "")

Rel(testManagerService, dbContent, "", "")
Rel(testManagerService, notificater, "", "")

Rel(statisticsService, dbStatistics, "", "")

Rel(notificater, notificaterInternal, "", "")

Rel(backupService, dbStatistics, "", "")
Rel(backupService, dbContent, "", "")
Rel(backupService, backupServiceInternal, "", "")

Rel(communicationService, dbContent, "", "")

Rel(crone, backupService, "", "")
 
@enduml