@startuml 
title "C4. Сервис управления контентом"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Boundary(contentManagerService, "Сервис управления контентом") {

' Domain доменные сущности в основе бизнес-логики
    System_Boundary(Domain, "Domain") {
        Component(course, "Course", "", "")
        Component(chapter, "Chapter", "", "")
        Component(theme, "Theme", "", "")
        Component(attachmentFile, "Attachment", "", "")
        Component(review, "Review", "", "")
        Component(forum, "Forum", "", "")
        Component(test, "Test", "", "")
        Component(exam, "Exam", "", "")
    }

' APP модифицирование сущностей БЛ
    System_Boundary(APP, "APP") {
        Component(courseService, "AppCourse", "Application Service", "Управление курсами")
        Component(chapterService, "AppChapter", "Application Service", "Управление разделами")
        Component(themeService, "AppTheme", "Application Service", "Управление темами")
        Component(reviewService, "AppReview", "Application Service", "Управление отзывами")
        Component(forumService, "AppForum", "Application Service", "Управление форумами")
    }

' Infrastructure взаимодействие со сторонними сервисами
System_Boundary(Infrastructure, "Infrastructure") {
    Component(dbContent, "dbContentService", "PostgreSQL", "")
    Component(dbStatistics, "dbStatisticsService", "PostgreSQL", "")
    Component(notificater, "notificaterService", "GO", "")
    Component(communicationService, "communicationService", "GO", "")
    Component(backupService, "backupService", "GO", "")
    Component(viewVideoService,"videoService", "GO", "")
}


' Controller
    System_Boundary(Presentation, "Controller") {
        Component(webApp, "APIWebApp", "", "")
    }
}

' Внешние контейнеры
Component(dbStatistics, "База данных статистики", "PostgreSQL", "")
Component(dbContent, "База данных контента", "PostgreSQL", "")
Component(notificater, "Сервис уведомлений", "GO", "")
Component(communicationService, "Сервис обратной связи", "GO", "")
Component(viewVideoService, "Сервис отображения видео", "")

@enduml
