@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title C4 Infrastructure Diagram - Learning Management System (LMS)

System_Boundary(system_boundary, "LMS System") {
    Container(spa, "LMS Web Application", "React, JavaScript", "Клиентское веб-приложение с адаптивным дизайном")

    Container(http_server, "Nginx", "Nginx", "Сервер статики и обратный прокси")

    Container(app_server, "Backend API", "Node.js, Express", "Серверная часть приложения, предоставляющая API")

    ContainerDb(database, "Application Database", "PostgreSQL", "База данных приложения")

    Container(auth_service, "Authentication Service", "Node.js, Express", "Сервис аутентификации и авторизации")

    Container(content_service, "Content Management Service", "Node.js, Express", "Сервис управления учебным контентом")

    Container(notification_service, "Notification Service", "Node.js, Express", "Сервис отправки уведомлений")
}

System_Ext(email_service, "Email Delivery Service", "SMTP", "Сервис отправки электронных писем")

System_Ext(sms_service, "SMS Gateway", "External API", "Сервис отправки SMS сообщений")

System_Ext(sso_provider, "SSO Provider", "OAuth2/OpenID Connect", "Сервис единого входа для пользователей")

System_Ext(storage_service, "File Storage Service", "AWS S3 or similar", "Облачное хранилище для учебного контента")


Rel(spa, http_server, "Запросы статики и API", "HTTPS")
Rel(http_server, spa, "Обслуживание статики", "HTTPS")
Rel(http_server, app_server, "Проксирование API запросов", "HTTP")

Rel(app_server, auth_service, "Аутентификация и авторизация", "HTTP/REST")
Rel(app_server, content_service, "Управление контентом", "HTTP/REST")
Rel(app_server, notification_service, "Отправка уведомлений", "HTTP/REST")
Rel(app_server, database, "Чтение и запись данных", "JDBC/SSL")

Rel(auth_service, database, "Хранение данных пользователей", "JDBC/SSL")
Rel(auth_service, sso_provider, "Проверка учетных данных", "OAuth2/OpenID Connect")

Rel(content_service, database, "Хранение метаданных контента", "JDBC/SSL")
Rel(content_service, storage_service, "Хранение файлов контента", "S3 API")

Rel(notification_service, email_service, "Отправка email уведомлений", "SMTP")
Rel(notification_service, sms_service, "Отправка SMS уведомлений", "HTTP API")

@enduml
